name: weirdbuggames_quickstock
description: "This mobile application aims to develop an Android-based sales and inventory management system for retail stores. Currently, retail stores manage their inventory and sales using paper-based or non-existent systems. This makes tracking inventory levels and sales data time-consuming as the store grows. This application will allow sari-sari store owners to manage their inventory, record sales transactions, and generate sales reports using a mobile application. Key features include adding, editing, and removing inventory items, recording product sales, and visualizing daily sales and monthly total sales. The system is designed to work offline. As Android is widely used, it will be the exclusive platform. The goal is to provide sari-sari store owners with a simple way to streamline their operations by digitizing paper-based processes. The user interface will be easy to use for all ages. This aims to improve business processes and access to real-time inventory and sales information."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.0.8
  intl: ^0.19.0
  share: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  crypto: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/